listener 1883 0.0.0.0
allow_anonymous true

listener 8883 0.0.0.0
cafile D:\New folder\ICS-Guard\infrastructure\mosquitto\config\certs\ca.crt
certfile D:\New folder\ICS-Guard\infrastructure\mosquitto\config\certs\server.crt
keyfile D:\New folder\ICS-Guard\infrastructure\mosquitto\config\certs\server.key
tls_version tlsv1.3
