export const NOTIFICATION_POLLING_INTERVAL = 5000;

export const NOTIFICATION_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

export const NOTIFICATION_TYPE = {
  ALERT: 'ALERT',
  WARNING: 'WARNING',
  INFO: 'INFO',
  SYSTEM: 'SYSTEM',
  DEVICE: 'DEVICE',
};
