export const AUTH_CONSTANTS = {
  LOGIN_MAX_ATTEMPTS: 5,
  LOCKOUT_WINDOW_MS: 5 * 60 * 1000,
  LOCKOUT_MINUTES: 15,
  JWT_ACCESS_EXPIRY_DEFAULT: '2h',
  JWT_REFRESH_EXPIRY_DEFAULT: '1d',
  ACCESS_TOKEN_COOKIE: 'access_token',
  REFRESH_TOKEN_COOKIE: 'refresh_token'
};

export const AUTH_PROVIDERS = {
  LOCAL: 'local',
  GOOGLE: 'google'
};
