export const REMEDIATION_SESSION_SOURCES = {
  AI: 'ai',
  MANUAL: 'manual',
  HYBRID: 'hybrid',
  SYSTEM: 'system',
};

export const REMEDIATION_PLAN_STATUSES = {
  DRAFT: 'draft',
  PENDING_APPROVAL: 'pending_approval',
  READY: 'ready',
  RUNNING: 'running',
  PARTIALLY_COMPLETED: 'partially_completed',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
  ROLLED_BACK: 'rolled_back',
};

export const REMEDIATION_STEP_STATUSES = {
  PENDING: 'pending',
  APPROVED: 'approved',
  RUNNING: 'running',
  COMPLETED: 'completed',
  FAILED: 'failed',
  SKIPPED: 'skipped',
  ROLLED_BACK: 'rolled_back',
};

export const REMEDIATION_ACTION_KEYS = {
  MANUAL_CHECK: 'MANUAL_CHECK',
  RUN_HEALTH_CHECK: 'RUN_HEALTH_CHECK',
  ISOLATE_DEVICE: 'ISOLATE_DEVICE',
  BLOCK_DEVICE_TRAFFIC: 'BLOCK_DEVICE_TRAFFIC',
  STOP_ATTACK_SIMULATION: 'STOP_ATTACK_SIMULATION',
  RESTORE_DEVICE_NETWORK: 'RESTORE_DEVICE_NETWORK',
  ROLLBACK_DEVICE: 'ROLLBACK_DEVICE',
  VERIFY_RECOVERY: 'VERIFY_RECOVERY',
};

export const REMEDIATION_ACTION_TYPES = {
  DIAGNOSE: 'diagnose',
  CONTAINMENT: 'containment',
  RECOVERY: 'recovery',
  VERIFICATION: 'verification',
  MANUAL: 'manual',
};

export const REMEDIATION_ACTOR_TYPES = {
  AI: 'ai',
  USER: 'user',
  SYSTEM: 'system',
};

export const REMEDIATION_CASE_OUTCOMES = {
  SUCCESS: 'success',
  FAILED: 'failed',
  PARTIAL: 'partial',
};

export const REMEDIATION_DANGEROUS_ACTIONS = [
  REMEDIATION_ACTION_KEYS.ISOLATE_DEVICE,
  REMEDIATION_ACTION_KEYS.RESTORE_DEVICE_NETWORK,
  REMEDIATION_ACTION_KEYS.ROLLBACK_DEVICE,
];

export const REMEDIATION_AUTO_SAFE_ACTIONS = [
  REMEDIATION_ACTION_KEYS.MANUAL_CHECK,
  REMEDIATION_ACTION_KEYS.RUN_HEALTH_CHECK,
  REMEDIATION_ACTION_KEYS.BLOCK_DEVICE_TRAFFIC,
  REMEDIATION_ACTION_KEYS.STOP_ATTACK_SIMULATION,
  REMEDIATION_ACTION_KEYS.VERIFY_RECOVERY,
];

export const REMEDIATION_DEFAULT_AUTO_THRESHOLD = 3;
